import FWCore.ParameterSet.Config as cms

#    muons = cms.InputTag("cleanPatTrackerMuonsTriggerMatch"),
#    muJets = cms.InputTag("TrackerMuJetProducer05"),

LeptonJetAnalyzer = cms.EDAnalyzer('LeptonJetAnalyzer',
    analyzerDebug = cms.int32(1),
    fillGenLevel = cms.bool(True),
    muons = cms.InputTag("cleanPatPFMuonsTriggerMatch"),
    muJets = cms.InputTag("PFMuJetProducer05"),
    electrons = cms.InputTag("cleanPatPFElectronsTriggerMatch"),
    eleJets = cms.InputTag("PFEleJetProducer05"),
    DiMuons_Iso_Max = cms.double(2.0),
    DiElectrons_Iso_Max = cms.double(2.0),
    nThrowsConsistentVertexesCalculator = cms.int32(100000),
    hltPaths = cms.vstring([
		'HLT_DoubleMu18NoFiltersNoVtx_v1', 
		'HLT_DoubleMu23NoFiltersNoVtxDisplaced_v1', 
		'HLT_DoubleMu28NoFiltersNoVtxDisplaced_v1', 
		'HLT_DoubleMu33NoFiltersNoVtx_v1', 
		'HLT_DoubleMu38NoFiltersNoVtx_v1', 
		'HLT_DoubleMu4_3_Bs_v1', 
		'HLT_DoubleMu4_3_Jpsi_Displaced_v1', 
		'HLT_DoubleMu4_JpsiTrk_Displaced_v1', 
		'HLT_DoubleMu4_LowMassNonResonantTrk_Displaced_v1', 
		'HLT_DoubleMu4_PsiPrimeTrk_Displaced_v1', 
		'HLT_DoubleMu8_Mass8_PFHT300_v1', 
		'HLT_Mu12_Photon25_CaloIdL_L1ISO_v1', 
		'HLT_Mu12_Photon25_CaloIdL_L1OR_v1', 
		'HLT_Mu12_Photon25_CaloIdL_v1', 
		'HLT_Mu16_TkMu0_dEta18_Onia_v1', 
		'HLT_Mu16_TkMu0_dEta18_Phi_v1', 
		'HLT_Mu17_Mu8_DZ_v1', 
		'HLT_Mu17_Mu8_SameSign_DPhi_v1', 
		'HLT_Mu17_Mu8_SameSign_v1', 
		'HLT_Mu17_Photon30_CaloIdL_L1ISO_v1', 
		'HLT_Mu17_Photon35_CaloIdL_L1ISO_v1', 
		'HLT_Mu17_TkMu8_DZ_v1', 
		'HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v1', 
		'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_v1', 
		'HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_v1', 
		'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_v1', 
		'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_v1', 
		'HLT_Mu17_TrkIsoVVL_v1', 
		'HLT_Mu23NoFiltersNoVtx_Photon23_CaloIdL_v1', 
		'HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v1', 
		'HLT_Mu24_TrkIsoVVL_v1', 
		'HLT_Mu25_TkMu0_dEta18_Onia_v1', 
		'HLT_Mu28NoFiltersNoVtxDisplaced_Photon28_CaloIdL_v1', 
		'HLT_Mu28NoFiltersNoVtx_CentralCaloJet40_v1', 
		'HLT_Mu28NoFiltersNoVtx_DisplacedJet40_Loose_v1', 
		'HLT_Mu30_Ele30_CaloIdL_GsfTrkIdVL_v1', 
		'HLT_Mu33NoFiltersNoVtxDisplaced_DisplacedJet50_Loose_v1', 
		'HLT_Mu33NoFiltersNoVtxDisplaced_DisplacedJet50_Tight_v1', 
		'HLT_Mu33NoFiltersNoVtxDisplaced_Photon33_CaloIdL_v1', 
		'HLT_Mu38NoFiltersNoVtxDisplaced_DisplacedJet60_Loose_v1', 
		'HLT_Mu38NoFiltersNoVtxDisplaced_DisplacedJet60_Tight_v1', 
		'HLT_Mu38NoFiltersNoVtx_DisplacedJet60_Loose_v1', 
		'HLT_Mu38NoFiltersNoVtx_Photon38_CaloIdL_v1', 
		'HLT_Mu40_TkMu11_v1', 
		'HLT_Mu42NoFiltersNoVtx_Photon42_CaloIdL_v1', 
		'HLT_Mu7p5_L2Mu2_Jpsi_v1', 
		'HLT_Mu7p5_L2Mu2_Upsilon_v1', 
		'HLT_Mu7p5_Track2_Jpsi_v1', 
		'HLT_Mu7p5_Track2_Upsilon_v1', 
		'HLT_Mu7p5_Track3p5_Jpsi_v1', 
		'HLT_Mu7p5_Track3p5_Upsilon_v1', 
		'HLT_Mu7p5_Track7_Jpsi_v1', 
		'HLT_Mu7p5_Track7_Upsilon_v1', 
		'HLT_Mu8_DiEle12_CaloIdL_TrackIdL_v1', 
		'HLT_Mu8_Ele8_CaloIdM_TrackIdM_Mass8_PFHT300_v1', 
		'HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL_v1', 
		'HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_v1', 
		'HLT_TrkMu15_DoubleTrkMu5NoFiltersNoVtx_v1', 
		'HLT_TrkMu17_DoubleTrkMu8NoFiltersNoVtx_v1', 
        ]
    )
)
