void eff_hlt_RECO_vs_leading_phi_()
{
//=========Macro generated from canvas: c/c
//=========  (Tue Oct 10 10:24:48 2017) by ROOT version6.06/01
   TCanvas *c = new TCanvas("c", "c",0,23,700,500);
   gStyle->SetOptStat(0);
   c->Range(-3.926991,-0.13125,3.926991,1.18125);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   TH1F *__3 = new TH1F("__3","CMS Preliminary leading muon #phi, 2016B-H",60,-3.141593,3.141593);
   __3->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   __3->SetLineColor(ci);
   __3->GetXaxis()->SetTitle("Leading muon #phi");
   __3->GetXaxis()->SetLabelFont(42);
   __3->GetXaxis()->SetLabelSize(0.035);
   __3->GetXaxis()->SetTitleSize(0.035);
   __3->GetXaxis()->SetTitleFont(42);
   __3->GetYaxis()->SetTitle("HLT_TrkMu17_DoubleTrkMu8NoFiltersNoVtx efficiency");
   __3->GetYaxis()->SetLabelFont(42);
   __3->GetYaxis()->SetLabelSize(0.035);
   __3->GetYaxis()->SetTitleSize(0.035);
   __3->GetYaxis()->SetTitleFont(42);
   __3->GetZaxis()->SetLabelFont(42);
   __3->GetZaxis()->SetLabelSize(0.035);
   __3->GetZaxis()->SetTitleSize(0.035);
   __3->GetZaxis()->SetTitleFont(42);
   __3->Draw("");
   
   TEfficiency * RECO_leading_phi_fid_clone3 = new TEfficiency("RECO_leading_phi_fid_clone","",60,-3.141593,3.141593);
   
   RECO_leading_phi_fid_clone3->SetConfidenceLevel(0.6826895);
   RECO_leading_phi_fid_clone3->SetBetaAlpha(1);
   RECO_leading_phi_fid_clone3->SetBetaBeta(1);
   RECO_leading_phi_fid_clone3->SetWeight(1);
   RECO_leading_phi_fid_clone3->SetStatisticOption(0);
   RECO_leading_phi_fid_clone3->SetPosteriorMode(0);
   RECO_leading_phi_fid_clone3->SetShortestInterval(0);
   RECO_leading_phi_fid_clone3->SetTotalEvents(0,0);
   RECO_leading_phi_fid_clone3->SetPassedEvents(0,0);
   RECO_leading_phi_fid_clone3->SetTotalEvents(1,184);
   RECO_leading_phi_fid_clone3->SetPassedEvents(1,114);
   RECO_leading_phi_fid_clone3->SetTotalEvents(2,194);
   RECO_leading_phi_fid_clone3->SetPassedEvents(2,119);
   RECO_leading_phi_fid_clone3->SetTotalEvents(3,167);
   RECO_leading_phi_fid_clone3->SetPassedEvents(3,106);
   RECO_leading_phi_fid_clone3->SetTotalEvents(4,167);
   RECO_leading_phi_fid_clone3->SetPassedEvents(4,105);
   RECO_leading_phi_fid_clone3->SetTotalEvents(5,199);
   RECO_leading_phi_fid_clone3->SetPassedEvents(5,119);
   RECO_leading_phi_fid_clone3->SetTotalEvents(6,202);
   RECO_leading_phi_fid_clone3->SetPassedEvents(6,130);
   RECO_leading_phi_fid_clone3->SetTotalEvents(7,174);
   RECO_leading_phi_fid_clone3->SetPassedEvents(7,110);
   RECO_leading_phi_fid_clone3->SetTotalEvents(8,167);
   RECO_leading_phi_fid_clone3->SetPassedEvents(8,101);
   RECO_leading_phi_fid_clone3->SetTotalEvents(9,175);
   RECO_leading_phi_fid_clone3->SetPassedEvents(9,113);
   RECO_leading_phi_fid_clone3->SetTotalEvents(10,191);
   RECO_leading_phi_fid_clone3->SetPassedEvents(10,112);
   RECO_leading_phi_fid_clone3->SetTotalEvents(11,186);
   RECO_leading_phi_fid_clone3->SetPassedEvents(11,110);
   RECO_leading_phi_fid_clone3->SetTotalEvents(12,179);
   RECO_leading_phi_fid_clone3->SetPassedEvents(12,105);
   RECO_leading_phi_fid_clone3->SetTotalEvents(13,158);
   RECO_leading_phi_fid_clone3->SetPassedEvents(13,94);
   RECO_leading_phi_fid_clone3->SetTotalEvents(14,190);
   RECO_leading_phi_fid_clone3->SetPassedEvents(14,120);
   RECO_leading_phi_fid_clone3->SetTotalEvents(15,207);
   RECO_leading_phi_fid_clone3->SetPassedEvents(15,115);
   RECO_leading_phi_fid_clone3->SetTotalEvents(16,185);
   RECO_leading_phi_fid_clone3->SetPassedEvents(16,99);
   RECO_leading_phi_fid_clone3->SetTotalEvents(17,189);
   RECO_leading_phi_fid_clone3->SetPassedEvents(17,109);
   RECO_leading_phi_fid_clone3->SetTotalEvents(18,179);
   RECO_leading_phi_fid_clone3->SetPassedEvents(18,112);
   RECO_leading_phi_fid_clone3->SetTotalEvents(19,171);
   RECO_leading_phi_fid_clone3->SetPassedEvents(19,92);
   RECO_leading_phi_fid_clone3->SetTotalEvents(20,192);
   RECO_leading_phi_fid_clone3->SetPassedEvents(20,104);
   RECO_leading_phi_fid_clone3->SetTotalEvents(21,174);
   RECO_leading_phi_fid_clone3->SetPassedEvents(21,106);
   RECO_leading_phi_fid_clone3->SetTotalEvents(22,169);
   RECO_leading_phi_fid_clone3->SetPassedEvents(22,100);
   RECO_leading_phi_fid_clone3->SetTotalEvents(23,182);
   RECO_leading_phi_fid_clone3->SetPassedEvents(23,109);
   RECO_leading_phi_fid_clone3->SetTotalEvents(24,173);
   RECO_leading_phi_fid_clone3->SetPassedEvents(24,107);
   RECO_leading_phi_fid_clone3->SetTotalEvents(25,202);
   RECO_leading_phi_fid_clone3->SetPassedEvents(25,122);
   RECO_leading_phi_fid_clone3->SetTotalEvents(26,203);
   RECO_leading_phi_fid_clone3->SetPassedEvents(26,120);
   RECO_leading_phi_fid_clone3->SetTotalEvents(27,187);
   RECO_leading_phi_fid_clone3->SetPassedEvents(27,120);
   RECO_leading_phi_fid_clone3->SetTotalEvents(28,189);
   RECO_leading_phi_fid_clone3->SetPassedEvents(28,110);
   RECO_leading_phi_fid_clone3->SetTotalEvents(29,176);
   RECO_leading_phi_fid_clone3->SetPassedEvents(29,105);
   RECO_leading_phi_fid_clone3->SetTotalEvents(30,204);
   RECO_leading_phi_fid_clone3->SetPassedEvents(30,121);
   RECO_leading_phi_fid_clone3->SetTotalEvents(31,197);
   RECO_leading_phi_fid_clone3->SetPassedEvents(31,106);
   RECO_leading_phi_fid_clone3->SetTotalEvents(32,182);
   RECO_leading_phi_fid_clone3->SetPassedEvents(32,111);
   RECO_leading_phi_fid_clone3->SetTotalEvents(33,153);
   RECO_leading_phi_fid_clone3->SetPassedEvents(33,100);
   RECO_leading_phi_fid_clone3->SetTotalEvents(34,160);
   RECO_leading_phi_fid_clone3->SetPassedEvents(34,97);
   RECO_leading_phi_fid_clone3->SetTotalEvents(35,198);
   RECO_leading_phi_fid_clone3->SetPassedEvents(35,118);
   RECO_leading_phi_fid_clone3->SetTotalEvents(36,178);
   RECO_leading_phi_fid_clone3->SetPassedEvents(36,102);
   RECO_leading_phi_fid_clone3->SetTotalEvents(37,179);
   RECO_leading_phi_fid_clone3->SetPassedEvents(37,115);
   RECO_leading_phi_fid_clone3->SetTotalEvents(38,166);
   RECO_leading_phi_fid_clone3->SetPassedEvents(38,105);
   RECO_leading_phi_fid_clone3->SetTotalEvents(39,175);
   RECO_leading_phi_fid_clone3->SetPassedEvents(39,98);
   RECO_leading_phi_fid_clone3->SetTotalEvents(40,175);
   RECO_leading_phi_fid_clone3->SetPassedEvents(40,114);
   RECO_leading_phi_fid_clone3->SetTotalEvents(41,180);
   RECO_leading_phi_fid_clone3->SetPassedEvents(41,111);
   RECO_leading_phi_fid_clone3->SetTotalEvents(42,169);
   RECO_leading_phi_fid_clone3->SetPassedEvents(42,102);
   RECO_leading_phi_fid_clone3->SetTotalEvents(43,169);
   RECO_leading_phi_fid_clone3->SetPassedEvents(43,90);
   RECO_leading_phi_fid_clone3->SetTotalEvents(44,183);
   RECO_leading_phi_fid_clone3->SetPassedEvents(44,112);
   RECO_leading_phi_fid_clone3->SetTotalEvents(45,177);
   RECO_leading_phi_fid_clone3->SetPassedEvents(45,104);
   RECO_leading_phi_fid_clone3->SetTotalEvents(46,189);
   RECO_leading_phi_fid_clone3->SetPassedEvents(46,111);
   RECO_leading_phi_fid_clone3->SetTotalEvents(47,181);
   RECO_leading_phi_fid_clone3->SetPassedEvents(47,99);
   RECO_leading_phi_fid_clone3->SetTotalEvents(48,206);
   RECO_leading_phi_fid_clone3->SetPassedEvents(48,98);
   RECO_leading_phi_fid_clone3->SetTotalEvents(49,176);
   RECO_leading_phi_fid_clone3->SetPassedEvents(49,107);
   RECO_leading_phi_fid_clone3->SetTotalEvents(50,194);
   RECO_leading_phi_fid_clone3->SetPassedEvents(50,116);
   RECO_leading_phi_fid_clone3->SetTotalEvents(51,200);
   RECO_leading_phi_fid_clone3->SetPassedEvents(51,122);
   RECO_leading_phi_fid_clone3->SetTotalEvents(52,167);
   RECO_leading_phi_fid_clone3->SetPassedEvents(52,98);
   RECO_leading_phi_fid_clone3->SetTotalEvents(53,159);
   RECO_leading_phi_fid_clone3->SetPassedEvents(53,98);
   RECO_leading_phi_fid_clone3->SetTotalEvents(54,160);
   RECO_leading_phi_fid_clone3->SetPassedEvents(54,86);
   RECO_leading_phi_fid_clone3->SetTotalEvents(55,195);
   RECO_leading_phi_fid_clone3->SetPassedEvents(55,106);
   RECO_leading_phi_fid_clone3->SetTotalEvents(56,169);
   RECO_leading_phi_fid_clone3->SetPassedEvents(56,89);
   RECO_leading_phi_fid_clone3->SetTotalEvents(57,177);
   RECO_leading_phi_fid_clone3->SetPassedEvents(57,110);
   RECO_leading_phi_fid_clone3->SetTotalEvents(58,172);
   RECO_leading_phi_fid_clone3->SetPassedEvents(58,93);
   RECO_leading_phi_fid_clone3->SetTotalEvents(59,166);
   RECO_leading_phi_fid_clone3->SetPassedEvents(59,101);
   RECO_leading_phi_fid_clone3->SetTotalEvents(60,202);
   RECO_leading_phi_fid_clone3->SetPassedEvents(60,113);
   RECO_leading_phi_fid_clone3->SetTotalEvents(61,0);
   RECO_leading_phi_fid_clone3->SetPassedEvents(61,0);
   RECO_leading_phi_fid_clone3->SetFillColor(19);

   ci = TColor::GetColor("#0000ff");
   RECO_leading_phi_fid_clone3->SetLineColor(ci);

   ci = TColor::GetColor("#0000ff");
   RECO_leading_phi_fid_clone3->SetMarkerColor(ci);
   RECO_leading_phi_fid_clone3->SetMarkerStyle(7);
   RECO_leading_phi_fid_clone3->SetMarkerSize(5);
   RECO_leading_phi_fid_clone3->Draw("samep");
   
   TPaveText *pt = new TPaveText(0.15,0.9342405,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *AText = pt->AddText("CMS Preliminary leading muon #phi, 2016B-H");
   pt->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
