void eff_hlt_RECO_vs_leading_pT_()
{
//=========Macro generated from canvas: c/c
//=========  (Tue Oct 10 10:24:46 2017) by ROOT version6.06/01
   TCanvas *c = new TCanvas("c", "c",0,23,700,500);
   gStyle->SetOptStat(0);
   c->Range(-6.25,-0.13125,56.25,1.18125);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   TH1F *__1 = new TH1F("__1","CMS Preliminary leading muon p_{T}, 2016B-H",50,0,50);
   __1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   __1->SetLineColor(ci);
   __1->GetXaxis()->SetTitle("Leading muon p_{T} [GeV]");
   __1->GetXaxis()->SetLabelFont(42);
   __1->GetXaxis()->SetLabelSize(0.035);
   __1->GetXaxis()->SetTitleSize(0.035);
   __1->GetXaxis()->SetTitleFont(42);
   __1->GetYaxis()->SetTitle("HLT_TrkMu17_DoubleTrkMu8NoFiltersNoVtx efficiency");
   __1->GetYaxis()->SetLabelFont(42);
   __1->GetYaxis()->SetLabelSize(0.035);
   __1->GetYaxis()->SetTitleSize(0.035);
   __1->GetYaxis()->SetTitleFont(42);
   __1->GetZaxis()->SetLabelFont(42);
   __1->GetZaxis()->SetLabelSize(0.035);
   __1->GetZaxis()->SetTitleSize(0.035);
   __1->GetZaxis()->SetTitleFont(42);
   __1->Draw("");
   
   TEfficiency * RECO_leading_pt_fid_clone1 = new TEfficiency("RECO_leading_pt_fid_clone","",50,0,50);
   
   RECO_leading_pt_fid_clone1->SetConfidenceLevel(0.6826895);
   RECO_leading_pt_fid_clone1->SetBetaAlpha(1);
   RECO_leading_pt_fid_clone1->SetBetaBeta(1);
   RECO_leading_pt_fid_clone1->SetWeight(1);
   RECO_leading_pt_fid_clone1->SetStatisticOption(0);
   RECO_leading_pt_fid_clone1->SetPosteriorMode(0);
   RECO_leading_pt_fid_clone1->SetShortestInterval(0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(0,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(0,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(1,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(1,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(2,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(2,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(3,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(3,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(4,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(4,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(5,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(5,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(6,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(6,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(7,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(7,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(8,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(8,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(9,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(9,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(10,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(10,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(11,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(11,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(12,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(12,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(13,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(13,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(14,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(14,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(15,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(15,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(16,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(16,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(17,0);
   RECO_leading_pt_fid_clone1->SetPassedEvents(17,0);
   RECO_leading_pt_fid_clone1->SetTotalEvents(18,168);
   RECO_leading_pt_fid_clone1->SetPassedEvents(18,72);
   RECO_leading_pt_fid_clone1->SetTotalEvents(19,169);
   RECO_leading_pt_fid_clone1->SetPassedEvents(19,76);
   RECO_leading_pt_fid_clone1->SetTotalEvents(20,180);
   RECO_leading_pt_fid_clone1->SetPassedEvents(20,90);
   RECO_leading_pt_fid_clone1->SetTotalEvents(21,173);
   RECO_leading_pt_fid_clone1->SetPassedEvents(21,94);
   RECO_leading_pt_fid_clone1->SetTotalEvents(22,185);
   RECO_leading_pt_fid_clone1->SetPassedEvents(22,87);
   RECO_leading_pt_fid_clone1->SetTotalEvents(23,196);
   RECO_leading_pt_fid_clone1->SetPassedEvents(23,104);
   RECO_leading_pt_fid_clone1->SetTotalEvents(24,207);
   RECO_leading_pt_fid_clone1->SetPassedEvents(24,109);
   RECO_leading_pt_fid_clone1->SetTotalEvents(25,195);
   RECO_leading_pt_fid_clone1->SetPassedEvents(25,112);
   RECO_leading_pt_fid_clone1->SetTotalEvents(26,208);
   RECO_leading_pt_fid_clone1->SetPassedEvents(26,112);
   RECO_leading_pt_fid_clone1->SetTotalEvents(27,197);
   RECO_leading_pt_fid_clone1->SetPassedEvents(27,118);
   RECO_leading_pt_fid_clone1->SetTotalEvents(28,193);
   RECO_leading_pt_fid_clone1->SetPassedEvents(28,94);
   RECO_leading_pt_fid_clone1->SetTotalEvents(29,196);
   RECO_leading_pt_fid_clone1->SetPassedEvents(29,125);
   RECO_leading_pt_fid_clone1->SetTotalEvents(30,184);
   RECO_leading_pt_fid_clone1->SetPassedEvents(30,103);
   RECO_leading_pt_fid_clone1->SetTotalEvents(31,176);
   RECO_leading_pt_fid_clone1->SetPassedEvents(31,100);
   RECO_leading_pt_fid_clone1->SetTotalEvents(32,164);
   RECO_leading_pt_fid_clone1->SetPassedEvents(32,100);
   RECO_leading_pt_fid_clone1->SetTotalEvents(33,155);
   RECO_leading_pt_fid_clone1->SetPassedEvents(33,87);
   RECO_leading_pt_fid_clone1->SetTotalEvents(34,176);
   RECO_leading_pt_fid_clone1->SetPassedEvents(34,94);
   RECO_leading_pt_fid_clone1->SetTotalEvents(35,184);
   RECO_leading_pt_fid_clone1->SetPassedEvents(35,107);
   RECO_leading_pt_fid_clone1->SetTotalEvents(36,148);
   RECO_leading_pt_fid_clone1->SetPassedEvents(36,92);
   RECO_leading_pt_fid_clone1->SetTotalEvents(37,170);
   RECO_leading_pt_fid_clone1->SetPassedEvents(37,95);
   RECO_leading_pt_fid_clone1->SetTotalEvents(38,145);
   RECO_leading_pt_fid_clone1->SetPassedEvents(38,94);
   RECO_leading_pt_fid_clone1->SetTotalEvents(39,149);
   RECO_leading_pt_fid_clone1->SetPassedEvents(39,88);
   RECO_leading_pt_fid_clone1->SetTotalEvents(40,149);
   RECO_leading_pt_fid_clone1->SetPassedEvents(40,85);
   RECO_leading_pt_fid_clone1->SetTotalEvents(41,156);
   RECO_leading_pt_fid_clone1->SetPassedEvents(41,91);
   RECO_leading_pt_fid_clone1->SetTotalEvents(42,140);
   RECO_leading_pt_fid_clone1->SetPassedEvents(42,90);
   RECO_leading_pt_fid_clone1->SetTotalEvents(43,133);
   RECO_leading_pt_fid_clone1->SetPassedEvents(43,79);
   RECO_leading_pt_fid_clone1->SetTotalEvents(44,123);
   RECO_leading_pt_fid_clone1->SetPassedEvents(44,79);
   RECO_leading_pt_fid_clone1->SetTotalEvents(45,130);
   RECO_leading_pt_fid_clone1->SetPassedEvents(45,78);
   RECO_leading_pt_fid_clone1->SetTotalEvents(46,119);
   RECO_leading_pt_fid_clone1->SetPassedEvents(46,76);
   RECO_leading_pt_fid_clone1->SetTotalEvents(47,147);
   RECO_leading_pt_fid_clone1->SetPassedEvents(47,74);
   RECO_leading_pt_fid_clone1->SetTotalEvents(48,137);
   RECO_leading_pt_fid_clone1->SetPassedEvents(48,82);
   RECO_leading_pt_fid_clone1->SetTotalEvents(49,124);
   RECO_leading_pt_fid_clone1->SetPassedEvents(49,71);
   RECO_leading_pt_fid_clone1->SetTotalEvents(50,116);
   RECO_leading_pt_fid_clone1->SetPassedEvents(50,72);
   RECO_leading_pt_fid_clone1->SetTotalEvents(51,5477);
   RECO_leading_pt_fid_clone1->SetPassedEvents(51,3411);
   RECO_leading_pt_fid_clone1->SetFillColor(19);

   ci = TColor::GetColor("#0000ff");
   RECO_leading_pt_fid_clone1->SetLineColor(ci);

   ci = TColor::GetColor("#0000ff");
   RECO_leading_pt_fid_clone1->SetMarkerColor(ci);
   RECO_leading_pt_fid_clone1->SetMarkerStyle(7);
   RECO_leading_pt_fid_clone1->SetMarkerSize(5);
   RECO_leading_pt_fid_clone1->Draw("samep");
   
   TPaveText *pt = new TPaveText(0.15,0.916519,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *AText = pt->AddText("CMS Preliminary leading muon p_{T}, 2016B-H");
   pt->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
