void eff_hlt_RECO_vs_leading_eta_()
{
//=========Macro generated from canvas: c/c
//=========  (Tue Oct 10 10:24:47 2017) by ROOT version6.06/01
   TCanvas *c = new TCanvas("c", "c",0,23,700,500);
   gStyle->SetOptStat(0);
   c->Range(-3.125,-0.13125,3.125,1.18125);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   TH1F *__2 = new TH1F("__2","CMS Preliminary leading muon #eta, 2016B-H",50,-2.5,2.5);
   __2->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   __2->SetLineColor(ci);
   __2->GetXaxis()->SetTitle("Leading muon #eta");
   __2->GetXaxis()->SetLabelFont(42);
   __2->GetXaxis()->SetLabelSize(0.035);
   __2->GetXaxis()->SetTitleSize(0.035);
   __2->GetXaxis()->SetTitleFont(42);
   __2->GetYaxis()->SetTitle("HLT_TrkMu17_DoubleTrkMu8NoFiltersNoVtx efficiency");
   __2->GetYaxis()->SetLabelFont(42);
   __2->GetYaxis()->SetLabelSize(0.035);
   __2->GetYaxis()->SetTitleSize(0.035);
   __2->GetYaxis()->SetTitleFont(42);
   __2->GetZaxis()->SetLabelFont(42);
   __2->GetZaxis()->SetLabelSize(0.035);
   __2->GetZaxis()->SetTitleSize(0.035);
   __2->GetZaxis()->SetTitleFont(42);
   __2->Draw("");
   
   TEfficiency * RECO_leading_eta_fid_clone2 = new TEfficiency("RECO_leading_eta_fid_clone","",50,-2.5,2.5);
   
   RECO_leading_eta_fid_clone2->SetConfidenceLevel(0.6826895);
   RECO_leading_eta_fid_clone2->SetBetaAlpha(1);
   RECO_leading_eta_fid_clone2->SetBetaBeta(1);
   RECO_leading_eta_fid_clone2->SetWeight(1);
   RECO_leading_eta_fid_clone2->SetStatisticOption(0);
   RECO_leading_eta_fid_clone2->SetPosteriorMode(0);
   RECO_leading_eta_fid_clone2->SetShortestInterval(0);
   RECO_leading_eta_fid_clone2->SetTotalEvents(0,0);
   RECO_leading_eta_fid_clone2->SetPassedEvents(0,0);
   RECO_leading_eta_fid_clone2->SetTotalEvents(1,0);
   RECO_leading_eta_fid_clone2->SetPassedEvents(1,0);
   RECO_leading_eta_fid_clone2->SetTotalEvents(2,23);
   RECO_leading_eta_fid_clone2->SetPassedEvents(2,16);
   RECO_leading_eta_fid_clone2->SetTotalEvents(3,22);
   RECO_leading_eta_fid_clone2->SetPassedEvents(3,12);
   RECO_leading_eta_fid_clone2->SetTotalEvents(4,31);
   RECO_leading_eta_fid_clone2->SetPassedEvents(4,23);
   RECO_leading_eta_fid_clone2->SetTotalEvents(5,30);
   RECO_leading_eta_fid_clone2->SetPassedEvents(5,14);
   RECO_leading_eta_fid_clone2->SetTotalEvents(6,32);
   RECO_leading_eta_fid_clone2->SetPassedEvents(6,19);
   RECO_leading_eta_fid_clone2->SetTotalEvents(7,38);
   RECO_leading_eta_fid_clone2->SetPassedEvents(7,27);
   RECO_leading_eta_fid_clone2->SetTotalEvents(8,44);
   RECO_leading_eta_fid_clone2->SetPassedEvents(8,26);
   RECO_leading_eta_fid_clone2->SetTotalEvents(9,71);
   RECO_leading_eta_fid_clone2->SetPassedEvents(9,54);
   RECO_leading_eta_fid_clone2->SetTotalEvents(10,82);
   RECO_leading_eta_fid_clone2->SetPassedEvents(10,59);
   RECO_leading_eta_fid_clone2->SetTotalEvents(11,89);
   RECO_leading_eta_fid_clone2->SetPassedEvents(11,65);
   RECO_leading_eta_fid_clone2->SetTotalEvents(12,108);
   RECO_leading_eta_fid_clone2->SetPassedEvents(12,65);
   RECO_leading_eta_fid_clone2->SetTotalEvents(13,129);
   RECO_leading_eta_fid_clone2->SetPassedEvents(13,76);
   RECO_leading_eta_fid_clone2->SetTotalEvents(14,129);
   RECO_leading_eta_fid_clone2->SetPassedEvents(14,79);
   RECO_leading_eta_fid_clone2->SetTotalEvents(15,149);
   RECO_leading_eta_fid_clone2->SetPassedEvents(15,93);
   RECO_leading_eta_fid_clone2->SetTotalEvents(16,188);
   RECO_leading_eta_fid_clone2->SetPassedEvents(16,94);
   RECO_leading_eta_fid_clone2->SetTotalEvents(17,515);
   RECO_leading_eta_fid_clone2->SetPassedEvents(17,267);
   RECO_leading_eta_fid_clone2->SetTotalEvents(18,497);
   RECO_leading_eta_fid_clone2->SetPassedEvents(18,265);
   RECO_leading_eta_fid_clone2->SetTotalEvents(19,508);
   RECO_leading_eta_fid_clone2->SetPassedEvents(19,295);
   RECO_leading_eta_fid_clone2->SetTotalEvents(20,501);
   RECO_leading_eta_fid_clone2->SetPassedEvents(20,292);
   RECO_leading_eta_fid_clone2->SetTotalEvents(21,483);
   RECO_leading_eta_fid_clone2->SetPassedEvents(21,273);
   RECO_leading_eta_fid_clone2->SetTotalEvents(22,500);
   RECO_leading_eta_fid_clone2->SetPassedEvents(22,292);
   RECO_leading_eta_fid_clone2->SetTotalEvents(23,396);
   RECO_leading_eta_fid_clone2->SetPassedEvents(23,221);
   RECO_leading_eta_fid_clone2->SetTotalEvents(24,426);
   RECO_leading_eta_fid_clone2->SetPassedEvents(24,261);
   RECO_leading_eta_fid_clone2->SetTotalEvents(25,529);
   RECO_leading_eta_fid_clone2->SetPassedEvents(25,332);
   RECO_leading_eta_fid_clone2->SetTotalEvents(26,537);
   RECO_leading_eta_fid_clone2->SetPassedEvents(26,334);
   RECO_leading_eta_fid_clone2->SetTotalEvents(27,447);
   RECO_leading_eta_fid_clone2->SetPassedEvents(27,275);
   RECO_leading_eta_fid_clone2->SetTotalEvents(28,392);
   RECO_leading_eta_fid_clone2->SetPassedEvents(28,211);
   RECO_leading_eta_fid_clone2->SetTotalEvents(29,565);
   RECO_leading_eta_fid_clone2->SetPassedEvents(29,316);
   RECO_leading_eta_fid_clone2->SetTotalEvents(30,538);
   RECO_leading_eta_fid_clone2->SetPassedEvents(30,323);
   RECO_leading_eta_fid_clone2->SetTotalEvents(31,485);
   RECO_leading_eta_fid_clone2->SetPassedEvents(31,287);
   RECO_leading_eta_fid_clone2->SetTotalEvents(32,491);
   RECO_leading_eta_fid_clone2->SetPassedEvents(32,280);
   RECO_leading_eta_fid_clone2->SetTotalEvents(33,481);
   RECO_leading_eta_fid_clone2->SetPassedEvents(33,285);
   RECO_leading_eta_fid_clone2->SetTotalEvents(34,443);
   RECO_leading_eta_fid_clone2->SetPassedEvents(34,253);
   RECO_leading_eta_fid_clone2->SetTotalEvents(35,168);
   RECO_leading_eta_fid_clone2->SetPassedEvents(35,112);
   RECO_leading_eta_fid_clone2->SetTotalEvents(36,127);
   RECO_leading_eta_fid_clone2->SetPassedEvents(36,88);
   RECO_leading_eta_fid_clone2->SetTotalEvents(37,116);
   RECO_leading_eta_fid_clone2->SetPassedEvents(37,83);
   RECO_leading_eta_fid_clone2->SetTotalEvents(38,88);
   RECO_leading_eta_fid_clone2->SetPassedEvents(38,62);
   RECO_leading_eta_fid_clone2->SetTotalEvents(39,86);
   RECO_leading_eta_fid_clone2->SetPassedEvents(39,60);
   RECO_leading_eta_fid_clone2->SetTotalEvents(40,80);
   RECO_leading_eta_fid_clone2->SetPassedEvents(40,48);
   RECO_leading_eta_fid_clone2->SetTotalEvents(41,72);
   RECO_leading_eta_fid_clone2->SetPassedEvents(41,43);
   RECO_leading_eta_fid_clone2->SetTotalEvents(42,46);
   RECO_leading_eta_fid_clone2->SetPassedEvents(42,31);
   RECO_leading_eta_fid_clone2->SetTotalEvents(43,42);
   RECO_leading_eta_fid_clone2->SetPassedEvents(43,30);
   RECO_leading_eta_fid_clone2->SetTotalEvents(44,30);
   RECO_leading_eta_fid_clone2->SetPassedEvents(44,23);
   RECO_leading_eta_fid_clone2->SetTotalEvents(45,27);
   RECO_leading_eta_fid_clone2->SetPassedEvents(45,16);
   RECO_leading_eta_fid_clone2->SetTotalEvents(46,23);
   RECO_leading_eta_fid_clone2->SetPassedEvents(46,17);
   RECO_leading_eta_fid_clone2->SetTotalEvents(47,21);
   RECO_leading_eta_fid_clone2->SetPassedEvents(47,12);
   RECO_leading_eta_fid_clone2->SetTotalEvents(48,28);
   RECO_leading_eta_fid_clone2->SetPassedEvents(48,23);
   RECO_leading_eta_fid_clone2->SetTotalEvents(49,16);
   RECO_leading_eta_fid_clone2->SetPassedEvents(49,9);
   RECO_leading_eta_fid_clone2->SetTotalEvents(50,0);
   RECO_leading_eta_fid_clone2->SetPassedEvents(50,0);
   RECO_leading_eta_fid_clone2->SetTotalEvents(51,0);
   RECO_leading_eta_fid_clone2->SetPassedEvents(51,0);
   RECO_leading_eta_fid_clone2->SetFillColor(19);

   ci = TColor::GetColor("#0000ff");
   RECO_leading_eta_fid_clone2->SetLineColor(ci);

   ci = TColor::GetColor("#0000ff");
   RECO_leading_eta_fid_clone2->SetMarkerColor(ci);
   RECO_leading_eta_fid_clone2->SetMarkerStyle(7);
   RECO_leading_eta_fid_clone2->SetMarkerSize(5);
   RECO_leading_eta_fid_clone2->Draw("samep");
   
   TPaveText *pt = new TPaveText(0.15,0.9342405,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *AText = pt->AddText("CMS Preliminary leading muon #eta, 2016B-H");
   pt->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
