void rapidityfit()
{
//=========Macro generated from canvas: c/c
//=========  (Wed May 16 15:24:13 2018) by ROOT version6.06/01
   TCanvas *c = new TCanvas("c", "c",0,0,800,800);
   c->Range(-0.6882353,-4.971001,3.194118,29.82028);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetRightMargin(0.05);
   c->SetTopMargin(0.07);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   c->SetFrameFillStyle(0);
   c->SetFrameBorderMode(0);
   
   TH1F *diMuonC_Rapidity_RegionA__4 = new TH1F("diMuonC_Rapidity_RegionA__4","",50,-0.3,3);
   diMuonC_Rapidity_RegionA__4->SetBinContent(0,294.7714);
   diMuonC_Rapidity_RegionA__4->SetBinContent(1,9.825712);
   diMuonC_Rapidity_RegionA__4->SetBinContent(2,8.669746);
   diMuonC_Rapidity_RegionA__4->SetBinContent(3,9.247729);
   diMuonC_Rapidity_RegionA__4->SetBinContent(4,10.98168);
   diMuonC_Rapidity_RegionA__4->SetBinContent(5,11.55966);
   diMuonC_Rapidity_RegionA__4->SetBinContent(6,7.51378);
   diMuonC_Rapidity_RegionA__4->SetBinContent(7,12.71563);
   diMuonC_Rapidity_RegionA__4->SetBinContent(8,13.29361);
   diMuonC_Rapidity_RegionA__4->SetBinContent(9,10.98168);
   diMuonC_Rapidity_RegionA__4->SetBinContent(10,13.87159);
   diMuonC_Rapidity_RegionA__4->SetBinContent(11,7.51378);
   diMuonC_Rapidity_RegionA__4->SetBinContent(12,9.247729);
   diMuonC_Rapidity_RegionA__4->SetBinContent(13,5.779831);
   diMuonC_Rapidity_RegionA__4->SetBinContent(14,10.4037);
   diMuonC_Rapidity_RegionA__4->SetBinContent(15,8.669746);
   diMuonC_Rapidity_RegionA__4->SetBinContent(16,17.91747);
   diMuonC_Rapidity_RegionA__4->SetBinContent(17,13.87159);
   diMuonC_Rapidity_RegionA__4->SetBinContent(18,8.669746);
   diMuonC_Rapidity_RegionA__4->SetBinContent(19,9.825712);
   diMuonC_Rapidity_RegionA__4->SetBinContent(20,9.247729);
   diMuonC_Rapidity_RegionA__4->SetBinContent(21,16.18353);
   diMuonC_Rapidity_RegionA__4->SetBinContent(22,10.4037);
   diMuonC_Rapidity_RegionA__4->SetBinContent(23,9.825712);
   diMuonC_Rapidity_RegionA__4->SetBinContent(24,11.55966);
   diMuonC_Rapidity_RegionA__4->SetBinContent(25,9.825712);
   diMuonC_Rapidity_RegionA__4->SetBinContent(26,8.669746);
   diMuonC_Rapidity_RegionA__4->SetBinContent(27,17.33949);
   diMuonC_Rapidity_RegionA__4->SetBinContent(28,7.51378);
   diMuonC_Rapidity_RegionA__4->SetBinContent(29,11.55966);
   diMuonC_Rapidity_RegionA__4->SetBinContent(30,12.71563);
   diMuonC_Rapidity_RegionA__4->SetBinContent(31,10.4037);
   diMuonC_Rapidity_RegionA__4->SetBinContent(32,21.38537);
   diMuonC_Rapidity_RegionA__4->SetBinContent(33,10.4037);
   diMuonC_Rapidity_RegionA__4->SetBinContent(34,6.935797);
   diMuonC_Rapidity_RegionA__4->SetBinContent(35,7.51378);
   diMuonC_Rapidity_RegionA__4->SetBinContent(36,4.623865);
   diMuonC_Rapidity_RegionA__4->SetBinContent(37,9.247729);
   diMuonC_Rapidity_RegionA__4->SetBinContent(38,6.935797);
   diMuonC_Rapidity_RegionA__4->SetBinContent(39,4.045882);
   diMuonC_Rapidity_RegionA__4->SetBinContent(40,2.311932);
   diMuonC_Rapidity_RegionA__4->SetBinContent(41,0.5779831);
   diMuonC_Rapidity_RegionA__4->SetEntries(1219);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *AText = ptstats->AddText("diMuonC_Rapidity_RegionA");
   AText->SetTextSize(0.0368);
   AText = ptstats->AddText("Entries = 1219   ");
   AText = ptstats->AddText("Mean  = 0.9648");
   AText = ptstats->AddText("Std Dev   = 0.7106");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   diMuonC_Rapidity_RegionA__4->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(diMuonC_Rapidity_RegionA__4);
   diMuonC_Rapidity_RegionA__4->SetFillStyle(0);
   diMuonC_Rapidity_RegionA__4->SetLineStyle(0);
   diMuonC_Rapidity_RegionA__4->SetMarkerStyle(20);
   diMuonC_Rapidity_RegionA__4->GetXaxis()->SetTitle("di-#mu_{1} Rapidity");
   diMuonC_Rapidity_RegionA__4->GetXaxis()->SetLabelFont(42);
   diMuonC_Rapidity_RegionA__4->GetXaxis()->SetLabelOffset(0.007);
   diMuonC_Rapidity_RegionA__4->GetXaxis()->SetLabelSize(0.05);
   diMuonC_Rapidity_RegionA__4->GetXaxis()->SetTitleSize(0.06);
   diMuonC_Rapidity_RegionA__4->GetXaxis()->SetTitleFont(42);
   diMuonC_Rapidity_RegionA__4->GetYaxis()->SetTitle("Events");
   diMuonC_Rapidity_RegionA__4->GetYaxis()->SetLabelFont(42);
   diMuonC_Rapidity_RegionA__4->GetYaxis()->SetLabelOffset(0.007);
   diMuonC_Rapidity_RegionA__4->GetYaxis()->SetLabelSize(0.05);
   diMuonC_Rapidity_RegionA__4->GetYaxis()->SetTitleSize(0.06);
   diMuonC_Rapidity_RegionA__4->GetYaxis()->SetTitleOffset(1.1);
   diMuonC_Rapidity_RegionA__4->GetYaxis()->SetTitleFont(42);
   diMuonC_Rapidity_RegionA__4->GetZaxis()->SetLabelFont(42);
   diMuonC_Rapidity_RegionA__4->GetZaxis()->SetLabelOffset(0.007);
   diMuonC_Rapidity_RegionA__4->GetZaxis()->SetLabelSize(0.05);
   diMuonC_Rapidity_RegionA__4->GetZaxis()->SetTitleSize(0.06);
   diMuonC_Rapidity_RegionA__4->GetZaxis()->SetTitleFont(42);
   diMuonC_Rapidity_RegionA__4->Draw("Ep");
   
   TH1F *FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5 = new TH1F("FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5","",50,-0.3,3);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(1,10.4555);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(2,10.07806);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(3,10.33635);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(4,10.78412);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(5,9.679536);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(6,10.08531);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(7,10.35592);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(8,9.672218);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(9,10.74383);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(10,10.43955);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(11,10.81796);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(12,10.05446);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(13,10.80961);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(14,10.94561);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(15,10.43818);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(16,12.21111);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(17,11.18964);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(18,11.31212);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(19,11.50763);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(20,11.4443);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(21,11.84056);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(22,12.24009);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(23,11.48864);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(24,11.37088);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(25,10.47943);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(26,11.24441);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(27,11.19281);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(28,10.99297);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(29,11.4015);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(30,11.17289);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(31,10.61073);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(32,10.44694);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(33,9.826015);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(34,11.18016);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(35,9.690631);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(36,9.694473);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(37,7.776994);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(38,6.334873);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(39,4.512541);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(40,2.215299);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetBinContent(41,0.7412703);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetMaximum(30);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetEntries(50);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   AText = ptstats->AddText("diMuonC_Rapidity_RegionA");
   AText->SetTextSize(0.0368);
   AText = ptstats->AddText("Entries = 1219   ");
   AText = ptstats->AddText("Mean  = 0.9648");
   AText = ptstats->AddText("Std Dev   = 0.7106");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetFillStyle(0);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetLineStyle(0);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->SetMarkerStyle(20);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetXaxis()->SetTitle("di-#mu_{1} Rapidity");
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetXaxis()->SetLabelFont(42);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetXaxis()->SetLabelOffset(0.007);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetXaxis()->SetLabelSize(0.05);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetXaxis()->SetTitleSize(0.06);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetXaxis()->SetTitleFont(42);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetYaxis()->SetTitle("Events");
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetYaxis()->SetLabelFont(42);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetYaxis()->SetLabelOffset(0.007);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetYaxis()->SetLabelSize(0.05);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetYaxis()->SetTitleSize(0.06);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetYaxis()->SetTitleOffset(1.1);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetYaxis()->SetTitleFont(42);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetZaxis()->SetLabelFont(42);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetZaxis()->SetLabelOffset(0.007);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetZaxis()->SetLabelSize(0.05);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetZaxis()->SetTitleSize(0.06);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->GetZaxis()->SetTitleFont(42);
   FractionsPfitsPtosPhistcLsPdiMuonC_Rapidity_RegionA__5->Draw("same");
      tex = new TLatex(0.67,0.92,"35.9 fb^{-1} (13 TeV)");
tex->SetNDC();
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
