import FWCore.ParameterSet.Config as cms

patOutput = cms.OutputModule("PoolOutputModule",
outputCommands = cms.untracked.vstring("drop *",
                   "keep *_patMuons_*_*",
                   "keep *_cleanPatMuons_*_*",
                   "keep *_patTrigger_*_*",
                   "keep *_muonTriggerMatch*_*_*",
                   "keep *_patTriggerEvent_*_*",
                   "keep *_cleanPatMuonsTriggerMatch_*_*",

                   "keep *_muons_*_*",
                   "keep recoTracks_generalTracks_*_*",
                   "keep *_standAloneMuons_*_*",
                   "keep *_globalMuons_*_*",

                   "keep *_towerMaker_*_*",
                   "keep *_genParticles_*_*",
                   "keep *_generator_*_*",
                   "drop edmHepMCProduct_generator_*_*",
                   "keep *_cscSegments_*_*",
                   "keep *_dt4DSegments_*_*",
                   "keep *_TriggerResults_*_HLT",
                   "keep *_TriggerResults_*_HLT8E29",
                   "keep *_TriggerResults_*_REDIGI",
                   "keep *_TriggerResults_*_REDIGI36X",
                   "keep *_TriggerResults_*_REDIGI37X",
                   "keep L1AcceptBunchCrossings_*_*_*",
                   "keep L1GlobalTriggerReadoutRecord_gtDigis_*_*",
                   "keep *_offlineBeamSpot_*_*",
                   "keep *_offlinePrimaryVertices_*_*",
                   "keep *_offlinePrimaryVerticesWithBS_*_*",
                   "keep *_met_*_*",
                   "keep *_metHO_*_*",
                   "keep *_metNoHF_*_*",
                   "keep *_metNoHFHO_*_*",
                   "keep *_metOpt_*_*",
                   "keep *_metOptHO_*_*",
                   "keep *_metOptNoHF_*_*",
                   "keep *_metOptNoHFHO_*_*",
                   "keep *_genMetCalo_*_*",
                   "keep *_genMetCaloAndNonPrompt_*_*",
                   "keep *_genMetTrue_*_*",
                   "keep *_tcMet_*_*",
                   "keep *_pfMet_*_*",

                   # for re-doing MuonIdProducer offline
                   "keep recoTrackExtras_generalTracks_*_*",
                   "keep *_ecalRecHit_*_*",
                   "keep *_hbhereco_*_*",
                   "keep *_horeco_*_*",
                   ),
fileName = cms.untracked.string("REPLACEME.root"))
