import FWCore.ParameterSet.Config as cms

patOutput = cms.OutputModule("PoolOutputModule",
outputCommands = cms.untracked.vstring("drop *",
                   "keep *_generalTracks_*_*",
                   "keep *_towerMaker_*_*",
                   "keep *_muons_*_*",
                   "keep *_globalMuons_*_*",
                   "keep *_cleanPatMuonsNormalMuons_*_*",
                   "keep *_cleanPatMuonsTrackerMuons_*_*",
                   "keep *_cleanPatMuonsStandAloneDefault_*_*",
                   "keep *_cleanPatMuonsStandAloneSET_*_*",
                   "keep *_cleanPatMuonsTrackerConvMuons_*_*",
                   "keep *_genParticles_*_*",
                   "keep *_generator_*_*",
                   "keep *_g4SimHits_*_*",
                   "keep *_cscSegments_*_*",
                   "keep *_dt4DSegments_*_*",
                   "keep *_TriggerResults_*_HLT",
                   "keep L1AcceptBunchCrossings_*_*_*",
                   "keep L1GlobalTriggerReadoutRecord_gtDigis_*_*",
                   "keep *_offlineBeamSpot_*_*",
                   "keep *_offlinePrimaryVertices_*_*",
                   "keep *_offlinePrimaryVerticesWithBS_*_*",
                   "keep *_met_*_*",
                   "keep *_metHO_*_*",
                   "keep *_metNoHF_*_*",
                   "keep *_metNoHFHO_*_*",
                   "keep *_metOpt_*_*",
                   "keep *_metOptHO_*_*",
                   "keep *_metOptNoHF_*_*",
                   "keep *_metOptNoHFHO_*_*",
                   "keep *_genMetCalo_*_*",
                   "keep *_genMetCaloAndNonPrompt_*_*",
                   "keep *_genMetTrue_*_*",
                   "keep *_tcMet_*_*",
                   "keep *_pfMet_*_*",
                   ),
fileName = cms.untracked.string("REPLACEME.root"))
