void DarkSusy_mH_125_mGammaD_0400_cT_100_LHE_Higgs_m()
{
//=========Macro generated from canvas: cnv/cnv
//=========  (Sun May  6 01:34:40 2018) by ROOT version6.06/01
   TCanvas *cnv = new TCanvas("cnv", "cnv",1,1,904,904);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   cnv->SetHighLightColor(2);
   cnv->Range(1.784236,-0.24375,2.499296,1.63125);
   cnv->SetFillColor(0);
   cnv->SetBorderMode(0);
   cnv->SetBorderSize(2);
   cnv->SetLogx();
   cnv->SetTickx(1);
   cnv->SetTicky(1);
   cnv->SetLeftMargin(0.17);
   cnv->SetRightMargin(0.03);
   cnv->SetTopMargin(0.07);
   cnv->SetBottomMargin(0.13);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   cnv->SetFrameFillStyle(0);
   cnv->SetFrameBorderMode(0);
   
   TH1F *h_higgs_M_dummy__9 = new TH1F("h_higgs_M_dummy__9","h_higgs_M_dummy",220,80.5,300.5);
   h_higgs_M_dummy__9->SetMaximum(1.5);
   h_higgs_M_dummy__9->SetLineStyle(0);
   h_higgs_M_dummy__9->SetMarkerStyle(20);
   h_higgs_M_dummy__9->GetXaxis()->SetTitle("Mass of h [GeV]");
   h_higgs_M_dummy__9->GetXaxis()->SetMoreLogLabels();
   h_higgs_M_dummy__9->GetXaxis()->SetNdivisions(10);
   h_higgs_M_dummy__9->GetXaxis()->SetLabelFont(42);
   h_higgs_M_dummy__9->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy__9->GetXaxis()->SetLabelSize(0.03);
   h_higgs_M_dummy__9->GetXaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy__9->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_M_dummy__9->GetXaxis()->SetTitleFont(42);
   h_higgs_M_dummy__9->GetYaxis()->SetTitle("Fraction of events / 1 GeV");
   h_higgs_M_dummy__9->GetYaxis()->SetLabelFont(42);
   h_higgs_M_dummy__9->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy__9->GetYaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy__9->GetYaxis()->SetTitleOffset(1.35);
   h_higgs_M_dummy__9->GetYaxis()->SetTitleFont(42);
   h_higgs_M_dummy__9->GetZaxis()->SetLabelFont(42);
   h_higgs_M_dummy__9->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy__9->GetZaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy__9->GetZaxis()->SetTitleFont(42);
   h_higgs_M_dummy__9->Draw("");
   
   TH1F *h_higgs_M_dummy__10 = new TH1F("h_higgs_M_dummy__10","h_higgs_M_dummy",220,80.5,300.5);
   h_higgs_M_dummy__10->SetMaximum(1.5);
   h_higgs_M_dummy__10->SetLineStyle(0);
   h_higgs_M_dummy__10->SetMarkerStyle(20);
   h_higgs_M_dummy__10->GetXaxis()->SetTitle("Mass of h [GeV]");
   h_higgs_M_dummy__10->GetXaxis()->SetMoreLogLabels();
   h_higgs_M_dummy__10->GetXaxis()->SetNdivisions(10);
   h_higgs_M_dummy__10->GetXaxis()->SetLabelFont(42);
   h_higgs_M_dummy__10->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy__10->GetXaxis()->SetLabelSize(0.03);
   h_higgs_M_dummy__10->GetXaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy__10->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_M_dummy__10->GetXaxis()->SetTitleFont(42);
   h_higgs_M_dummy__10->GetYaxis()->SetTitle("Fraction of events / 1 GeV");
   h_higgs_M_dummy__10->GetYaxis()->SetLabelFont(42);
   h_higgs_M_dummy__10->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy__10->GetYaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy__10->GetYaxis()->SetTitleOffset(1.35);
   h_higgs_M_dummy__10->GetYaxis()->SetTitleFont(42);
   h_higgs_M_dummy__10->GetZaxis()->SetLabelFont(42);
   h_higgs_M_dummy__10->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy__10->GetZaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy__10->GetZaxis()->SetTitleFont(42);
   h_higgs_M_dummy__10->Draw("same");
   
   TH1F *h_higgs_M__11 = new TH1F("h_higgs_M__11","h_higgs_M",10,120.5,130.5);
   h_higgs_M__11->SetBinContent(5,1);
   h_higgs_M__11->SetBinError(5,0.003535556);
   h_higgs_M__11->SetEntries(79999);
   h_higgs_M__11->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   h_higgs_M__11->SetLineColor(ci);
   h_higgs_M__11->SetLineWidth(2);
   h_higgs_M__11->SetMarkerStyle(20);
   h_higgs_M__11->GetXaxis()->SetLabelFont(42);
   h_higgs_M__11->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_M__11->GetXaxis()->SetTitleSize(0.06);
   h_higgs_M__11->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_M__11->GetXaxis()->SetTitleFont(42);
   h_higgs_M__11->GetYaxis()->SetLabelFont(42);
   h_higgs_M__11->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_M__11->GetYaxis()->SetTitleSize(0.06);
   h_higgs_M__11->GetYaxis()->SetTitleOffset(1.3);
   h_higgs_M__11->GetYaxis()->SetTitleFont(42);
   h_higgs_M__11->GetZaxis()->SetLabelFont(42);
   h_higgs_M__11->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_M__11->GetZaxis()->SetTitleSize(0.06);
   h_higgs_M__11->GetZaxis()->SetTitleFont(42);
   h_higgs_M__11->Draw("SAMEHIST");
   
   TH1F *h_higgs_M__12 = new TH1F("h_higgs_M__12","h_higgs_M",10,120.5,130.5);
   h_higgs_M__12->SetBinContent(5,1);
   h_higgs_M__12->SetBinError(5,0.003535556);
   h_higgs_M__12->SetEntries(79999);
   h_higgs_M__12->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   h_higgs_M__12->SetLineColor(ci);
   h_higgs_M__12->SetLineWidth(2);
   h_higgs_M__12->SetMarkerStyle(20);
   h_higgs_M__12->GetXaxis()->SetMoreLogLabels();
   h_higgs_M__12->GetXaxis()->SetLabelFont(42);
   h_higgs_M__12->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_M__12->GetXaxis()->SetTitleSize(0.06);
   h_higgs_M__12->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_M__12->GetXaxis()->SetTitleFont(42);
   h_higgs_M__12->GetYaxis()->SetLabelFont(42);
   h_higgs_M__12->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_M__12->GetYaxis()->SetTitleSize(0.06);
   h_higgs_M__12->GetYaxis()->SetTitleOffset(1.3);
   h_higgs_M__12->GetYaxis()->SetTitleFont(42);
   h_higgs_M__12->GetZaxis()->SetLabelFont(42);
   h_higgs_M__12->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_M__12->GetZaxis()->SetTitleSize(0.06);
   h_higgs_M__12->GetZaxis()->SetTitleFont(42);
   h_higgs_M__12->Draw("SAMEHIST");
   
   TLegend *leg = new TLegend(0.4566667,0.82,0.7822222,0.9066667,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.02777778);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","#splitline{pp #rightarrow h #rightarrow 2n_{1} #rightarrow 2n_{D} + 2 #gamma_{D} #rightarrow 2n_{D} + 4#mu}{#splitline{m_{h} = 125 GeV, m_{n_{1}} = 10 GeV, m_{n_{D}} = 1 GeV}{m_{#gamma_{D}} = 0.4 GeV, c#tau_{#gamma_{D}} = 1. mm}}","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.17,0.935,0.97,1,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextAlign(22);
   leg->SetTextSize(0.045);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("NULL","CMS Simulation (LHE) 13 TeV","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   TH1F *h_higgs_M_dummy__13 = new TH1F("h_higgs_M_dummy__13","h_higgs_M_dummy",220,80.5,300.5);
   h_higgs_M_dummy__13->SetMaximum(1.5);
   h_higgs_M_dummy__13->SetLineStyle(0);
   h_higgs_M_dummy__13->SetMarkerStyle(20);
   h_higgs_M_dummy__13->GetXaxis()->SetTitle("Mass of h [GeV]");
   h_higgs_M_dummy__13->GetXaxis()->SetMoreLogLabels();
   h_higgs_M_dummy__13->GetXaxis()->SetNdivisions(10);
   h_higgs_M_dummy__13->GetXaxis()->SetLabelFont(42);
   h_higgs_M_dummy__13->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy__13->GetXaxis()->SetLabelSize(0.03);
   h_higgs_M_dummy__13->GetXaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy__13->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_M_dummy__13->GetXaxis()->SetTitleFont(42);
   h_higgs_M_dummy__13->GetYaxis()->SetTitle("Fraction of events / 1 GeV");
   h_higgs_M_dummy__13->GetYaxis()->SetLabelFont(42);
   h_higgs_M_dummy__13->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy__13->GetYaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy__13->GetYaxis()->SetTitleOffset(1.35);
   h_higgs_M_dummy__13->GetYaxis()->SetTitleFont(42);
   h_higgs_M_dummy__13->GetZaxis()->SetLabelFont(42);
   h_higgs_M_dummy__13->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_M_dummy__13->GetZaxis()->SetTitleSize(0.06);
   h_higgs_M_dummy__13->GetZaxis()->SetTitleFont(42);
   h_higgs_M_dummy__13->Draw("same");
   
   TH1F *h_higgs_M__14 = new TH1F("h_higgs_M__14","h_higgs_M",10,120.5,130.5);
   h_higgs_M__14->SetBinContent(5,1);
   h_higgs_M__14->SetBinError(5,0.003535556);
   h_higgs_M__14->SetEntries(79999);
   h_higgs_M__14->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   h_higgs_M__14->SetLineColor(ci);
   h_higgs_M__14->SetLineWidth(2);
   h_higgs_M__14->SetMarkerStyle(20);
   h_higgs_M__14->GetXaxis()->SetMoreLogLabels();
   h_higgs_M__14->GetXaxis()->SetLabelFont(42);
   h_higgs_M__14->GetXaxis()->SetLabelOffset(0.007);
   h_higgs_M__14->GetXaxis()->SetTitleSize(0.06);
   h_higgs_M__14->GetXaxis()->SetTitleOffset(0.95);
   h_higgs_M__14->GetXaxis()->SetTitleFont(42);
   h_higgs_M__14->GetYaxis()->SetLabelFont(42);
   h_higgs_M__14->GetYaxis()->SetLabelOffset(0.007);
   h_higgs_M__14->GetYaxis()->SetTitleSize(0.06);
   h_higgs_M__14->GetYaxis()->SetTitleOffset(1.3);
   h_higgs_M__14->GetYaxis()->SetTitleFont(42);
   h_higgs_M__14->GetZaxis()->SetLabelFont(42);
   h_higgs_M__14->GetZaxis()->SetLabelOffset(0.007);
   h_higgs_M__14->GetZaxis()->SetTitleSize(0.06);
   h_higgs_M__14->GetZaxis()->SetTitleFont(42);
   h_higgs_M__14->Draw("SAMEHIST");
   cnv->Modified();
   cnv->cd();
   cnv->SetSelected(cnv);
}
